-- MySQL Script generated by MySQL Workbench
-- 04/11/16 20:00:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tinder
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tinder
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tinder` DEFAULT CHARACTER SET utf8 ;
USE `tinder` ;

-- -----------------------------------------------------
-- Table `tinder`.`chats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tinder`.`chats` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 80
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tinder`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tinder`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password_hash` CHAR(32) NOT NULL,
  `age` INT(11) NOT NULL,
  `gender_is_male` TINYINT(1) NOT NULL DEFAULT '1',
  `avatar_name` VARCHAR(255) NULL DEFAULT 'avatar_default.jpg',
  `email` VARCHAR(45) NOT NULL,
  `wants_male` TINYINT(1) NULL DEFAULT '0',
  `wants_female` TINYINT(1) NULL DEFAULT '0',
  `latitude` DOUBLE NULL DEFAULT NULL,
  `longitude` DOUBLE NULL DEFAULT NULL,
  `search_distance` INT(11) NULL DEFAULT '5',
  `max_desired_age` INT(11) NULL DEFAULT '22',
  `min_desired_age` INT(11) NULL DEFAULT '18',
  `full_name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uc_UserUE` (`username` ASC, `email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 934
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tinder`.`dislikes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tinder`.`dislikes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `disliker_id` INT(11) NOT NULL,
  `disliked_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uc_DisLikeID` (`disliker_id` ASC, `disliked_id` ASC),
  INDEX `fk_disliker_user_idx` (`disliker_id` ASC),
  INDEX `fk_disliked_user_idx` (`disliked_id` ASC),
  CONSTRAINT `fk_disliked_user`
    FOREIGN KEY (`disliked_id`)
    REFERENCES `tinder`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disliker_user`
    FOREIGN KEY (`disliker_id`)
    REFERENCES `tinder`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tinder`.`facebook_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tinder`.`facebook_users` (
  `id` VARCHAR(255) NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_facebook_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_facebook_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `tinder`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tinder`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tinder`.`likes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `liker_id` INT(11) NOT NULL,
  `liked_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uc_LikeID` (`liker_id` ASC, `liked_id` ASC),
  INDEX `fk_likes_liker_users_idx` (`liker_id` ASC),
  INDEX `fk_likes_liked_users_idx` (`liked_id` ASC),
  CONSTRAINT `fk_likes_liked_users`
    FOREIGN KEY (`liked_id`)
    REFERENCES `tinder`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_likes_liker_users`
    FOREIGN KEY (`liker_id`)
    REFERENCES `tinder`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 84
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tinder`.`match-notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tinder`.`match-notification` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_one` INT(11) NOT NULL,
  `user_two` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_match_user_one_idx` (`user_one` ASC),
  INDEX `fk_match_user_two_idx` (`user_two` ASC),
  CONSTRAINT `fk_match_user_one`
    FOREIGN KEY (`user_one`)
    REFERENCES `tinder`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_match_user_two`
    FOREIGN KEY (`user_two`)
    REFERENCES `tinder`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tinder`.`message-notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tinder`.`message-notifications` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `from_user_id` INT(11) NOT NULL,
  `to_user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_notif_from_user_idx` (`from_user_id` ASC),
  INDEX `fk_notif_to_user_idx` (`to_user_id` ASC),
  CONSTRAINT `fk_notif_from_user`
    FOREIGN KEY (`from_user_id`)
    REFERENCES `tinder`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notif_to_user`
    FOREIGN KEY (`to_user_id`)
    REFERENCES `tinder`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 59
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tinder`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tinder`.`messages` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `sender_id` INT(11) NOT NULL,
  `chat_id` INT(11) NOT NULL,
  `message` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_messages_chats_idx` (`chat_id` ASC),
  INDEX `fk_messages_users_idx` (`sender_id` ASC),
  CONSTRAINT `fk_messages_chats`
    FOREIGN KEY (`chat_id`)
    REFERENCES `tinder`.`chats` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_messages_users`
    FOREIGN KEY (`sender_id`)
    REFERENCES `tinder`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 237
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tinder`.`pictures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tinder`.`pictures` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `owner_id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_picture_owner_idx` (`owner_id` ASC),
  CONSTRAINT `fk_picture_owner`
    FOREIGN KEY (`owner_id`)
    REFERENCES `tinder`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 66
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tinder`.`unconfirmed_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tinder`.`unconfirmed_users` (
  `uuid` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password_hash` CHAR(32) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `gender_is_male` TINYINT(1) NULL DEFAULT '1',
  `age` INT(11) NULL DEFAULT '18',
  `full_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tinder`.`users_in_chats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tinder`.`users_in_chats` (
  `user_id` INT(11) NOT NULL,
  `chat_id` INT(11) NOT NULL,
  PRIMARY KEY (`user_id`, `chat_id`),
  INDEX `fk_Users_has_Chats1_Chats1_idx` (`chat_id` ASC),
  INDEX `fk_Users_has_Chats1_Users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Users_has_Chats1_Chats1`
    FOREIGN KEY (`chat_id`)
    REFERENCES `tinder`.`chats` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Chats1_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `tinder`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
